from uuid import UUID

from pydantic import BaseModel, Field


class AITreatmentOption(BaseModel):
    """A database treatment option supplied to the AI for selection only."""

    id: UUID
    name: str = Field(min_length=1)
    specialty: str = Field(min_length=1)
    description: str = Field(min_length=1)


class AIRecommendation(BaseModel):
    """Structured treatment-routing recommendation generated by the AI service."""

    patient_summary: str = Field(min_length=1)
    recommended_treatment_ids: list[UUID] = Field(min_length=1, max_length=2)
    ai_reasoning: str | None = None
